from __future__ import annotations

import json
from pathlib import Path
from pprint import pformat

from .models import LocalRecife


REPO_ROOT = Path(__file__).resolve().parents[2]
BACKEND_SYNC_PATH = REPO_ROOT / 'backend' / 'aquaculture' / 'generated_admin_sync.py'
FRONTEND_SYNC_PATH = REPO_ROOT / 'frontend' / 'src' / 'data' / 'recifeData.js'


def _arquivo_url(field_file) -> str:
    return field_file.url if field_file else ''


def _credito_imagem(especie) -> str:
    if especie.credito_imagem:
        return especie.credito_imagem
    if especie.foto:
        return 'Acervo local do projeto'
    return ''


def _fonte_imagem_url(especie) -> str:
    if especie.fonte_imagem_url:
        return especie.fonte_imagem_url
    return _arquivo_url(especie.foto)


def _serialize_especie(especie) -> dict:
    return {
        'id': especie.id,
        'nome_comum': especie.nome_comum,
        'nome_cientifico': especie.nome_cientifico,
        'tipo': especie.tipo,
        'descricao': especie.descricao,
        # ⚠️ So o que tem procedencia entra na copia versionada. Uma categoria
        # sem ano dentro de um .js e a pior combinacao possivel: ela sobrevive
        # a limpeza do banco e reaparece quando a API cai.
        'iucn_categoria': especie.iucn_categoria if especie.iucn_tem_procedencia else '',
        'iucn_avaliado_em': especie.iucn_avaliado_em,
        'iucn_versao': especie.iucn_versao,
        'fonte_iucn_url': especie.fonte_iucn_url,
        'iucn_tem_procedencia': especie.iucn_tem_procedencia,
        'foto_url': _arquivo_url(especie.foto),
        'credito_imagem': _credito_imagem(especie),
        'fonte_imagem_url': _fonte_imagem_url(especie),
        'fonte_url': especie.fonte_url or '',
    }


def build_sync_payload() -> dict:
    locais = LocalRecife.objects.prefetch_related('especies').order_by('nome')

    recifes = []
    detalhes = {}

    for local in locais:
        especies = [
            _serialize_especie(especie)
            for especie in local.especies.order_by('nome_comum', 'nome_cientifico')
        ]
        recifes.append(
            {
                'slug': local.slug,
                'nome': local.nome,
                'estado': local.estado,
                'cidade': local.cidade,
                'descricao': local.descricao,
                'imagem_url': _arquivo_url(local.imagem),
                'ultima_atualizacao': (
                    local.ultima_atualizacao.isoformat() if local.ultima_atualizacao else None
                ),
                'informacoes_disponiveis': len(especies),
            }
        )

        detalhes[local.slug] = {'especies': especies}

    return {
        'recifes': recifes,
        'detalhes': detalhes,
    }


def render_backend_sync(payload: dict) -> str:
    return (
        '"""Auto-generated by Django admin sync. Do not edit manually."""\n\n'
        f"SYNC_RECIFES = {pformat(payload['recifes'], sort_dicts=False, width=100)}\n\n"
        f"SYNC_DETALHES = {pformat(payload['detalhes'], sort_dicts=False, width=100)}\n"
    )


def render_frontend_sync(payload: dict) -> str:
    recifes = json.dumps(payload['recifes'], ensure_ascii=False, indent=2)
    detalhes = json.dumps(payload['detalhes'], ensure_ascii=False, indent=2)
    return (
        '// Auto-generated by Django admin sync. Do not edit manually.\n'
        f'export const FALLBACK_RECIFES = {recifes};\n\n'
        f'export const FALLBACK_DETALHES = {detalhes};\n'
    )


def _write_if_changed(path: Path, content: str) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    previous = path.read_text(encoding='utf-8') if path.exists() else None
    if previous == content:
        return False

    path.write_text(content, encoding='utf-8', newline='\n')
    return True


def sync_project_code_from_db(
    *,
    backend_output_path: str | Path | None = None,
    frontend_output_path: str | Path | None = None,
) -> dict:
    payload = build_sync_payload()
    backend_path = Path(backend_output_path) if backend_output_path else BACKEND_SYNC_PATH
    frontend_path = Path(frontend_output_path) if frontend_output_path else FRONTEND_SYNC_PATH

    backend_changed = _write_if_changed(backend_path, render_backend_sync(payload))
    frontend_changed = _write_if_changed(frontend_path, render_frontend_sync(payload))

    return {
        'backend_path': str(backend_path),
        'frontend_path': str(frontend_path),
        'backend_changed': backend_changed,
        'frontend_changed': frontend_changed,
        'payload': payload,
    }
