"""
Django settings for coral_site project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import re
import sys
from pathlib import Path

try:
    import environ
except ImportError as exc:  # pragma: no cover - depende do ambiente, nao do codigo
    # Quase sempre significa "esqueci de ativar o venv". O traceback padrao do
    # Django para isso e um ModuleNotFoundError no meio de dez frames de
    # importlib, que nao sugere a causa nem o conserto.
    raise ImportError(
        'Nao foi possivel importar "environ" (django-environ).\n\n'
        f'Python em uso: {sys.executable}\n\n'
        'Se esse caminho nao aponta para a pasta venv do projeto, o ambiente '
        'virtual nao esta ativo. Ative com:\n'
        '    .\\venv\\Scripts\\activate\n\n'
        'Se estiver ativo e o erro continuar, instale as dependencias:\n'
        '    pip install -r requirements.txt'
    ) from exc

from django.core.exceptions import ImproperlyConfigured

# ⚠️ Importado aqui, e nao dentro do bloco de log la embaixo: um import no meio
# do arquivo esconde a dependencia de quem le o topo. O modulo so usa `sys` e a
# biblioteca padrao — nao toca em Django nem em app, entao e seguro no tempo de
# settings, quando o registro de apps ainda nao existe.
from observabilidade import config as observabilidade_config

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()

# Le backend/.env quando existir. Variaveis reais de processo tem precedencia.
environ.Env.read_env(BASE_DIR / '.env')

# Chave de linha do .env: o mesmo formato que o django-environ reconhece.
_LINHA_DO_ENV = re.compile(r'\A(?:export )?([A-Za-z_0-9]+)=')


def _aparar_valores_do_env(caminho):
    """Remove espaco em branco nas pontas dos valores vindos do `.env`.

    🚨 **O django-environ nao faz isso, e o resultado e um erro que aponta
    para o lugar errado.** Ele le a linha com `(.*)\\Z` e so descasca aspas —
    um espaco sobrando no fim sobrevive ate o valor final. Aconteceu em
    29/07/2026, num `.env` montado por copiar-e-colar:

        DATABASE_URL=postgres://.../coral_brasil<espaco>

    O PostgreSQL respondeu `FATAL: database "coral_brasil " does not exist`, e
    a leitura natural dessa mensagem e "o banco nao foi criado" — manda quem
    esta diagnosticando conferir o Docker, que estava certo o tempo todo. A
    unica pista era o espaco entre o `l` e a aspa.

    O mesmo caractere em `NEO4J_PASSWORD` produziria "credencial invalida" com
    a senha certa digitada, e em `NOAA_ERDDAP_DATASET`, um 404.

    ⚠️ **So mexe nas chaves que o proprio `backend/.env` declara.** Varrer
    `os.environ` inteiro alteraria variaveis do sistema que nao sao nossas —
    e espaco no fim de uma delas pode ser deliberado. Aqui nao pode: nenhum
    valor deste projeto termina em espaco de proposito.
    """
    if not caminho.exists():
        return ()

    aparadas = []
    for linha in caminho.read_text(encoding='utf-8').splitlines():
        casa = _LINHA_DO_ENV.match(linha)
        if not casa:
            continue
        chave = casa.group(1)
        valor = os.environ.get(chave)
        if valor is not None and valor != valor.strip():
            os.environ[chave] = valor.strip()
            aparadas.append(chave)
    return tuple(aparadas)


ENV_APARADAS = _aparar_valores_do_env(BASE_DIR / '.env')

DEBUG = env.bool('DJANGO_DEBUG', default=False)

# Uma variavel definida como vazia (`DJANGO_SECRET_KEY=` no .env) nao cai no
# default do django-environ: ele devolve string vazia. Sem este tratamento, um
# .env copiado do exemplo trocaria a mensagem clara abaixo por um
# "SECRET_KEY must not be empty" do proprio Django, bem mais dificil de ligar
# a causa.
_secret_key = env('DJANGO_SECRET_KEY', default='').strip()

# Fail fast: fora de DEBUG, rodar sem SECRET_KEY explicita e um erro de
# configuracao, nao algo para silenciar com um fallback inseguro.
if _secret_key:
    SECRET_KEY = _secret_key
elif DEBUG:
    SECRET_KEY = 'django-insecure-apenas-para-desenvolvimento-local'
else:
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY nao esta definida (ou esta vazia) e DJANGO_DEBUG '
        'e False.\n\n'
        'Para desenvolvimento local, crie backend/.env com:\n'
        '    DJANGO_DEBUG=True\n'
        '    DJANGO_SECRET_KEY=<chave>\n\n'
        'Gere a chave com:\n'
        '    python -c "from django.core.management.utils import '
        'get_random_secret_key as k; print(k())"\n\n'
        'Veja backend/.env.example. O arquivo .env nao e versionado.'
    )

ALLOWED_HOSTS = env.list(
    'DJANGO_ALLOWED_HOSTS',
    default=['localhost', '127.0.0.1'],
)

OFFLINE_MODE = env.bool('OFFLINE_MODE', default=False)

# Permite a exportacao do banco para arquivos de codigo (recifeData.js).
# Desligado por padrao: editar dados nao deve reescrever arquivos-fonte.
ENABLE_CODE_SYNC = env.bool('ENABLE_CODE_SYNC', default=False)

# Integracoes externas desativadas por padrao durante a reestruturacao local.
USE_S3_STORAGE = False
ENABLE_AWS_SERVICES = False
ENABLE_EXTERNAL_TASKS = False

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'aquaculture',
    'corsheaders',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 🚨 Antes de tudo que possa falhar. Uma excecao levantada por um
    # middleware acima deste sairia sem correlacao — e um 500 sem rastro e
    # exatamente o caso em que o rastro faz falta.
    'observabilidade.middleware.CorrelacaoMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'coral_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'coral_site.wsgi.application'

# Banco configurado por URL, para que a troca SQLite -> PostgreSQL seja uma
# mudanca de ambiente e nao de codigo. Ex.:
#   DATABASE_URL=postgres://usuario:senha@localhost:5432/coral_brasil
# Para PostgreSQL, descomente psycopg no requirements.txt.
DATABASES = {
    'default': env.db_url(
        'DATABASE_URL',
        default=f'sqlite:///{(BASE_DIR / "db.sqlite3").as_posix()}',
    )
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CORS_ALLOWED_ORIGINS = env.list(
    'CORS_ALLOWED_ORIGINS',
    default=['http://localhost:3000'],
)

CSRF_TRUSTED_ORIGINS = env.list(
    'CSRF_TRUSTED_ORIGINS',
    default=[
        'https://projetocoralbrasil.com.br',
        'https://www.projetocoralbrasil.com.br',
    ],
)

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# --- Seguranca de transporte -----------------------------------------------
# Ativas por padrao fora de DEBUG. Podem ser desligadas por ambiente quando o
# TLS e terminado num proxy reverso ou num teste local com DEBUG=False.
SECURE_SSL_REDIRECT = env.bool('DJANGO_SECURE_SSL_REDIRECT', default=not DEBUG)
SESSION_COOKIE_SECURE = env.bool('DJANGO_SESSION_COOKIE_SECURE', default=not DEBUG)
CSRF_COOKIE_SECURE = env.bool('DJANGO_CSRF_COOKIE_SECURE', default=not DEBUG)

# HSTS: comeca em 0 de proposito. So aumente (ex.: 31536000 = 1 ano) depois de
# confirmar que todo o dominio, incluindo subdominios, serve HTTPS - o header
# e praticamente irreversivel do lado do navegador.
SECURE_HSTS_SECONDS = env.int('DJANGO_SECURE_HSTS_SECONDS', default=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
    'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False
)
SECURE_HSTS_PRELOAD = env.bool('DJANGO_SECURE_HSTS_PRELOAD', default=False)

# Confia no cabecalho do proxy reverso para detectar HTTPS (Heroku, Render,
# nginx). Sem isto, SECURE_SSL_REDIRECT entra em loop atras de um proxy.
if env.bool('DJANGO_BEHIND_PROXY', default=False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# --- Cache ------------------------------------------------------------------
# ⚠️ **Por processo (`LocMemCache`) por padrao, e nao Redis.** O projeto roda
# hoje num processo so; exigir Redis para o painel funcionar trocaria uma
# otimizacao por uma dependencia de infraestrutura nova, e a diretriz e a
# oposta (docs/DIRETRIZES.md secao 2.2). `CACHE_URL` promove para Redis quando
# houver mais de um processo — sem isso, cada worker manteria a sua copia, o
# que continua **correto** (a chave inclui a assinatura do dado) e so aproveita
# menos.
#
# 🚨 O que este cache NAO faz: expirar por tempo. A invalidacao e pela chave,
# que carrega a assinatura da serie. Ver `backend/memoria/__init__.py`.
_CACHE_URL = env('CACHE_URL', default='')
if _CACHE_URL:
    CACHES = {'default': env.cache_url('CACHE_URL')}
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'coral-painel',
            # Teto de itens. Sao ~10 locais x 1 entrada por dia; 500 e folga
            # larga e impede que uma chave mal montada encha a memoria.
            'OPTIONS': {'MAX_ENTRIES': 500},
        }
    }

# --- Observabilidade --------------------------------------------------------
# 🚨 Ate 12/08/2026 este bloco nao existia, e o efeito nao era "log feio": era
# log **invisivel**. As chamadas de `logger.warning` em `ingestao/`, `ml/` e
# `db/` caiam na configuracao implicita do Django — apareciam no `runserver` e
# sumiam sob cron, que e justamente onde `manage.py atualizar` roda.
#
# O detalhe de cada decisao esta em `observabilidade/config.py`.
_RODANDO_TESTE = observabilidade_config.rodando_teste()

LOG_PASTA = Path(env('LOG_PASTA', default=str(BASE_DIR / 'logs')))
LOG_NIVEL = env('LOG_NIVEL', default='DEBUG' if DEBUG else 'INFO').upper()

# ⚠️ Na suite, o console cai para WARNING. Nao e cosmetica: os testes de
# ingestao exercitam de proposito os caminhos de falha, e em INFO cada um
# imprime as linhas do fluxo inteiro no meio do relatorio do runner. Saida de
# teste que ninguem consegue ler e saida de teste que ninguem le - e ai o
# proximo erro real passa despercebido entre centenas de linhas esperadas.
# WARNING mantem visivel o que nao era esperado.
LOG_NIVEL_CONSOLE = env(
    'LOG_NIVEL_CONSOLE',
    default='WARNING' if _RODANDO_TESTE else LOG_NIVEL,
).upper()

# ⚠️ Desligado durante a suite de testes por padrao. Sem isto, rodar os testes
# passaria a escrever em `backend/logs/`, e um clone recem-clonado deixaria de
# ser identico a um clone que ja rodou a suite — a mesma classe de defeito que
# derrubou o CI em 30/07, quando dois testes so passavam em maquina que ja
# tinha feito a ingestao.
LOG_EM_ARQUIVO = env.bool('LOG_EM_ARQUIVO', default=not _RODANDO_TESTE)

# Nivel por dominio: LOG_NIVEL_INGESTAO=DEBUG deixa so a ingestao falante.
_NIVEIS_POR_DOMINIO = {
    dominio: env(f'LOG_NIVEL_{dominio.upper()}', default=LOG_NIVEL).upper()
    for dominio in observabilidade_config.DOMINIOS
}

LOGGING = observabilidade_config.montar(
    base_dir=BASE_DIR,
    nivel=LOG_NIVEL,
    nivel_console=LOG_NIVEL_CONSOLE,
    pasta=LOG_PASTA,
    em_arquivo=LOG_EM_ARQUIVO,
    rotacao_mb=env.int('LOG_ROTACAO_MB', default=observabilidade_config.ROTACAO_MB_PADRAO),
    backups=env.int('LOG_BACKUPS', default=observabilidade_config.BACKUPS_PADRAO),
    niveis_por_dominio=_NIVEIS_POR_DOMINIO,
)

# --- Fontes externas de dados (pipeline de ingestao) ------------------------
# Servidor e dataset andam em par: cada espelho ERDDAP publica o produto do
# Coral Reef Watch sob um identificador proprio.
#
# Padrao PACIOOS: e o unico espelho que responde dentro e fora de rede com
# dominio federal, e o backfill nos dois espelhos deu resultado identico bloco
# a bloco. Ver ingestao/conectores/noaa_crw.py para a evidencia completa.
NOAA_ERDDAP_SERVER = env(
    'NOAA_ERDDAP_SERVER',
    default='https://pae-paha.pacioos.hawaii.edu/erddap',
)
NOAA_ERDDAP_DATASET = env('NOAA_ERDDAP_DATASET', default='dhw_5km')

# Quantas vezes tentar antes de desistir de uma fonte. Vale so para falhas
# passageiras (503, timeout); certificado invalido ou 403 falham de primeira.
# Ver backend/ingestao/retentativa.py.
INGESTAO_TENTATIVAS = env.int('INGESTAO_TENTATIVAS', default=3)

# Tamanho do bloco em que o periodo e fatiado antes de virar requisicao.
# Pedir seis anos de uma vez faz o ERDDAP responder 408/ReadTimeout.
INGESTAO_JANELA_DIAS = env.int('INGESTAO_JANELA_DIAS', default=180)

# Copernicus Marine. A biblioteca `copernicusmarine` le estas variaveis
# direto do ambiente; como o django-environ exporta o que le do .env para
# os.environ, basta declara-las la. Sao espelhadas aqui para que o comando
# `testar_fontes` consiga relatar se estao configuradas.
COPERNICUSMARINE_SERVICE_USERNAME = env(
    'COPERNICUSMARINE_SERVICE_USERNAME', default=''
)
COPERNICUSMARINE_SERVICE_PASSWORD = env(
    'COPERNICUSMARINE_SERVICE_PASSWORD', default=''
)

# Series coletadas do Copernicus. `kd490` fica de fora do padrao: so existe de
# 2023-11-15 em diante e nao tem reanalise, o que cortaria o treino de 6,5 para
# 2,7 anos. Ver docs/VARIAVEIS.md secao 3.5.
COPERNICUS_SERIES = env.list(
    'COPERNICUS_SERIES', default=['salinidade', 'oxigenio']
)

NEO4J_URI = env('NEO4J_URI', default='bolt://localhost:7687')
NEO4J_USER = env('NEO4J_USER', default='neo4j')
NEO4J_PASSWORD = env('NEO4J_PASSWORD', default='')

# ---------------------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------------------
# 🚨 **Paginacao e por view, e NAO global. A decisao tem historia.**
#
# `MedicaoAmbiental` tem 57.420 linhas e cresce 24 por dia. Sem paginacao, o
# endpoint devolveria a serie inteira numa resposta - alguns MB de JSON,
# montados em memoria antes de sair. Ate 27/07/2026 o projeto nao tinha
# `REST_FRAMEWORK` configurado, ou seja, paginacao desligada.
#
# A primeira tentativa foi ligar `DEFAULT_PAGINATION_CLASS` aqui. **Errado**, e
# tres testes existentes flagraram: isso troca a resposta de TODA lista de um
# array cru para um envelope `{count, results, ...}`. Os endpoints
# `/api/locais/`, `/api/datasets/`, `/api/especies/` e `/api/monitoramento/`
# ja sao consumidos pelo frontend como array — seria **quebra de contrato
# disfarcada de configuracao**.
#
# E eles nao precisam: tem 3, 9, 9 e 3 registros. O unico com volume e o das
# medicoes, que e novo e portanto nao tem contrato a quebrar.
#
# Regra que fica: **paginacao se liga onde ha volume**, declarada na view.
DRF_PAGE_SIZE = env.int('DRF_PAGE_SIZE', default=100)

# Teto de `page_size`. O parametro vem da query string: sem limite,
# `?page_size=999999` desfaz a paginacao a pedido do cliente.
DRF_MAX_PAGE_SIZE = env.int('DRF_MAX_PAGE_SIZE', default=1000)

# Primeira vez que o projeto declara REST_FRAMEWORK. So autenticacao — de
# proposito **nao** mexe em paginacao nem em permissao padrao (continua
# `AllowAny`), que e exatamente a mudanca que ja quebrou contrato uma vez
# (ver o comentario acima). Sessao porque o frontend em dev fala com a API
# via proxy do CRA (`frontend/package.json`, "proxy") — same-origin, sem o
# atrito de CORS/cookie entre dominios que token exigiria contornar.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# ---------------------------------------------------------------------------
# Painel de risco
# ---------------------------------------------------------------------------
# Qual artefato o endpoint /api/painel-risco/ carrega. E derivado e nao
# versionado: se nao existir no disco, o endpoint responde 503 pedindo
# "manage.py treinar_final" em vez de servir predicao de origem desconhecida.
PAINEL_MODELO = env('PAINEL_MODELO', default='entrega1_baa')

# 🚨 **O limiar de alerta e decisao de produto, e por isso mora aqui e vai no
# payload — nao esta escondido no codigo do modelo.**
#
# 🚨 **Substituido por uma ESCALA em 30/07/2026.** Ver `PAINEL_NIVEIS` abaixo.
# Este valor continua existindo porque `alerta` e `limiar` viajam no payload
# desde 27/07 e ha consumidor lendo os dois; ele passou a ser **derivado** do
# degrau que exige acao, e nao mais a decisao em si.
#
# O historico da decisao antiga, e por que ela caiu:
#
# Adotou-se 0,10 em 27/07/2026 com o criterio "priorizar antecedencia". A
# justificativa registrada dizia que 0,10 comprava o episodio de **nove dias**
# de Picaozinho em 2022. 🚨 **Era falso, e o erro so apareceu em 30/07**: a
# tabela de docs/RESULTADOS.md secao 22.9.2 saiu com duas linhas trocadas.
# 0,10 tambem perde o episodio de nove dias; o que ele recuperava sobre o 0,20
# era um episodio de **um dia** (Porto de Galinhas, 07/05/2020). O de nove
# dias so volta em 0,05.
#
# ⚠️ **Nao existe corte natural, e o 0,20 anterior nunca foi escolhido.** Ate a
# recalibracao, `class_weight='balanced'` empurrava a probabilidade para cima,
# o que equivale a baixar o limiar sem declarar: o 0,50 do `predict` operava
# como 0,20. O 0,20 herdou essa equivalencia — nao uma decisao.
#
# ⚠️ **Nenhum corte pega todos os episodios.** Um evento de Picaozinho
# (21–23/04/2026) escapa em todos os varridos. O teto ai e do modelo.
PAINEL_LIMIAR = env.float('PAINEL_LIMIAR', default=0.20)

# ---------------------------------------------------------------------------
# A escala de aviso
# ---------------------------------------------------------------------------
# 🚨 **Tres degraus em vez de um corte, decidido em 30/07/2026.** Um corte
# unico obrigava a escolher entre duas coisas que nao se conciliam:
#
#   - cobrir tudo  -> so 0,05 alcanca o teto do modelo (18/19 episodios),
#                     e ali metade dos avisos e falsa;
#   - ser levado a serio -> 0,20 acerta 7 em 10, mas descarta de proposito
#                     dois episodios que o modelo conseguia pegar.
#
# Com escala os dois deixam de competir: o degrau mais baixo garante cobertura
# **sem pedir acao**, e o mais alto pede acao com precisao para sustenta-la.
#
# Medido em 30/07/2026 sobre as predicoes fora da dobra (7.095 amostras):
#
#   corte  precisao  episodios  1o dia  atraso  falsos/ano/recife  dias/ano
#    0,05    0,498     18/19      19    0,45 d       27,0            53,7
#    0,20    0,719     16/19      16    1,50 d       10,0            35,5
#    0,50    0,826     14/19      10    4,94 d        4,5            25,7
#
# ⚠️ **Isto nao e o `RISCO_STATUS` legado de volta.** Aquele tinha quatro
# niveis herdados do `StatusPredicao` e nenhum numero por tras; foi removido em
# 28/07/2026. A diferenca nao e de forma, e de procedencia.
#
# O publico a que a escala responde esta declarado em docs/VISAO_GERAL.md
# secao 2.1. Reproduza o material com: python backend/manage.py limiar
#
# Deixe vazio para usar a escala canonica de `ml/niveis.py`.
PAINEL_NIVEIS = []
