"""
Django settings for coral_site project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import environ
from django.core.exceptions import ImproperlyConfigured

BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()

# Le backend/.env quando existir. Variaveis reais de processo tem precedencia.
environ.Env.read_env(BASE_DIR / '.env')

DEBUG = env.bool('DJANGO_DEBUG', default=False)

# Fail fast: fora de DEBUG, rodar sem SECRET_KEY explicita e um erro de
# configuracao, nao algo para silenciar com um fallback inseguro.
if DEBUG:
    SECRET_KEY = env(
        'DJANGO_SECRET_KEY',
        default='django-insecure-apenas-para-desenvolvimento-local',
    )
else:
    try:
        SECRET_KEY = env('DJANGO_SECRET_KEY')
    except environ.ImproperlyConfigured as exc:
        raise ImproperlyConfigured(
            'DJANGO_SECRET_KEY e obrigatoria quando DJANGO_DEBUG=False. '
            'Defina-a em backend/.env ou no ambiente antes de subir o servico.'
        ) from exc

ALLOWED_HOSTS = env.list(
    'DJANGO_ALLOWED_HOSTS',
    default=['localhost', '127.0.0.1'],
)

OFFLINE_MODE = env.bool('OFFLINE_MODE', default=False)

# Integracoes externas desativadas por padrao durante a reestruturacao local.
USE_S3_STORAGE = False
ENABLE_AWS_SERVICES = False
ENABLE_EXTERNAL_TASKS = False

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'aquaculture',
    'corsheaders',
    'rest_framework',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'coral_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'coral_site.wsgi.application'

# Banco configurado por URL, para que a troca SQLite -> PostgreSQL seja uma
# mudanca de ambiente e nao de codigo. Ex.:
#   DATABASE_URL=postgres://usuario:senha@localhost:5432/coral_brasil
# Para PostgreSQL, descomente psycopg no requirements.txt.
DATABASES = {
    'default': env.db_url(
        'DATABASE_URL',
        default=f'sqlite:///{(BASE_DIR / "db.sqlite3").as_posix()}',
    )
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CORS_ALLOWED_ORIGINS = env.list(
    'CORS_ALLOWED_ORIGINS',
    default=['http://localhost:3000'],
)

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# --- Seguranca de transporte -----------------------------------------------
# Ativas por padrao fora de DEBUG. Podem ser desligadas por ambiente quando o
# TLS e terminado num proxy reverso ou num teste local com DEBUG=False.
SECURE_SSL_REDIRECT = env.bool('DJANGO_SECURE_SSL_REDIRECT', default=not DEBUG)
SESSION_COOKIE_SECURE = env.bool('DJANGO_SESSION_COOKIE_SECURE', default=not DEBUG)
CSRF_COOKIE_SECURE = env.bool('DJANGO_CSRF_COOKIE_SECURE', default=not DEBUG)

# HSTS: comeca em 0 de proposito. So aumente (ex.: 31536000 = 1 ano) depois de
# confirmar que todo o dominio, incluindo subdominios, serve HTTPS - o header
# e praticamente irreversivel do lado do navegador.
SECURE_HSTS_SECONDS = env.int('DJANGO_SECURE_HSTS_SECONDS', default=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
    'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', default=False
)
SECURE_HSTS_PRELOAD = env.bool('DJANGO_SECURE_HSTS_PRELOAD', default=False)

# Confia no cabecalho do proxy reverso para detectar HTTPS (Heroku, Render,
# nginx). Sem isto, SECURE_SSL_REDIRECT entra em loop atras de um proxy.
if env.bool('DJANGO_BEHIND_PROXY', default=False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

NEO4J_URI = env('NEO4J_URI', default='bolt://localhost:7687')
NEO4J_USER = env('NEO4J_USER', default='neo4j')
NEO4J_PASSWORD = env('NEO4J_PASSWORD', default='')
