// Auto-generated by Django admin sync. Do not edit manually.
export const FALLBACK_RECIFES = [
  {
    "slug": "abrolhos-ba",
    "nome": "Parque Nacional Marinho de Abrolhos",
    "estado": "Bahia",
    "cidade": "Caravelas",
    "descricao": "Area de referencia para monitoramento e biodiversidade coralinea.",
    "imagem_url": "",
    "ultima_atualizacao": "2026-04-14",
    "informacoes_disponiveis": 5,
    "possui_painel_risco": true
  },
  {
    "slug": "porto-de-galinhas-pe",
    "nome": "Piscinas Naturais de Porto de Galinhas",
    "estado": "Pernambuco",
    "cidade": "Ipojuca",
    "descricao": "Zona recifal turistica com ocorrencia de corais e peixes costeiros.",
    "imagem_url": "",
    "ultima_atualizacao": "2026-04-15",
    "informacoes_disponiveis": 1,
    "possui_painel_risco": true
  },
  {
    "slug": "picaozinho-pb",
    "nome": "Recife de Picaozinho",
    "estado": "Paraiba",
    "cidade": "Joao Pessoa",
    "descricao": "Recife costeiro raso com especies recifais e monitoramento ambiental.",
    "imagem_url": "",
    "ultima_atualizacao": "2026-04-10",
    "informacoes_disponiveis": 3,
    "possui_painel_risco": true
  }
];

export const FALLBACK_DETALHES = {
  "abrolhos-ba": {
    "especies": [
      {
        "id": 1,
        "nome_comum": "Coral-cerebro brasileiro",
        "nome_cientifico": "Mussismilia braziliensis",
        "tipo": "CORAL",
        "descricao": "Especie endemica do Brasil e importante formadora de recifes no Banco dos Abrolhos.",
        "status_conservacao": "Vulneravel",
        "foto_url": "/media/especies/Mussismilia_braziliensis.jpg",
        "credito_imagem": "Acervo local do projeto",
        "fonte_imagem_url": "https://www.inaturalist.org/observations/326387144",
        "fonte_url": ""
      },
      {
        "id": 2,
        "nome_comum": "Coral-estrela",
        "nome_cientifico": "Montastraea cavernosa",
        "tipo": "CORAL",
        "descricao": "Coral construtor frequente em substratos consolidados, relevante para a estrutura recifal.",
        "status_conservacao": "Pouco preocupante",
        "foto_url": "/media/especies/Montastraea_cavernosa.jpg",
        "credito_imagem": "Acervo local do projeto",
        "fonte_imagem_url": "https://www.inaturalist.org/observations/326387704",
        "fonte_url": ""
      },
      {
        "id": 8,
        "nome_comum": "Coral-fogo-vermelho",
        "nome_cientifico": "Muricea flamma",
        "tipo": "CORAL",
        "descricao": "Octocoral associado a ambientes recifais com boa circulacao de agua.",
        "status_conservacao": "Nao avaliado",
        "foto_url": "/media/especies/Muricea_flamma.jpg",
        "credito_imagem": "inaturalist.org",
        "fonte_imagem_url": "https://www.inaturalist.org/observations/137432286",
        "fonte_url": ""
      },
      {
        "id": 9,
        "nome_comum": "Coral-pilar",
        "nome_cientifico": "Dendrogyra cylindrus",
        "tipo": "CORAL",
        "descricao": "Coral de formato colunar com registros em areas recifais tropicais.",
        "status_conservacao": "Criticamente ameacado",
        "foto_url": "/media/especies/Dendrogyra_cylindrus.jpeg",
        "credito_imagem": "inaturalist.org",
        "fonte_imagem_url": "https://www.inaturalist.org/observations/276213882",
        "fonte_url": ""
      },
      {
        "id": 3,
        "nome_comum": "Peixe-anjo-rainha",
        "nome_cientifico": "Holacanthus ciliaris",
        "tipo": "PEIXE",
        "descricao": "Peixe recifal colorido, comum em ambientes coralineos com abrigo e alimento disponiveis.",
        "status_conservacao": "Nao avaliado",
        "foto_url": "/media/especies/Holacanthus_ciliaris.jpeg",
        "credito_imagem": "Acervo local do projeto",
        "fonte_imagem_url": "/media/especies/Holacanthus_ciliaris.jpeg",
        "fonte_url": ""
      }
    ],
    "monitoramento_recente": {
      "data": "2026-04-14",
      "sst_atual": 29.4,
      "limite_termico": 27.0,
      "anomalia": 2.4,
      "dhw_calculado": 6.3,
      "irradiancia": 31.8,
      "turbidez": 0.17,
      "salinidade": 36.1,
      "oxigenio": 6.42,
      "nitrato": 0.36,
      "clorofila": 0.64,
      "risco_integrado": 78.0,
      "nivel_alerta": "ALERTA_1"
    }
  },
  "porto-de-galinhas-pe": {
    "especies": [
      {
        "id": 7,
        "nome_comum": "Gorgonia-roxa",
        "nome_cientifico": "Phyllogorgia dilatata",
        "tipo": "CORAL",
        "descricao": "Gorgonia ramificada encontrada em ambientes recifais do litoral brasileiro.",
        "status_conservacao": "Nao avaliado",
        "foto_url": "/media/especies/Phyllogorgia_dilatata.jpg",
        "credito_imagem": "Acervo local do projeto",
        "fonte_imagem_url": "/media/especies/Phyllogorgia_dilatata.jpg",
        "fonte_url": ""
      }
    ],
    "monitoramento_recente": {
      "data": "2026-04-15",
      "sst_atual": 29.0,
      "limite_termico": 27.0,
      "anomalia": 2.0,
      "dhw_calculado": 5.1,
      "irradiancia": 30.4,
      "turbidez": 0.22,
      "salinidade": 35.9,
      "oxigenio": 6.27,
      "nitrato": 0.43,
      "clorofila": 0.71,
      "risco_integrado": 69.0,
      "nivel_alerta": "ALERTA_1"
    }
  },
  "picaozinho-pb": {
    "especies": [
      {
        "id": 4,
        "nome_comum": "Anemona-gigante",
        "nome_cientifico": "Condylactis gigantea",
        "tipo": "INVERTEBRADO",
        "descricao": "Invertebrado cnidario comum em ambientes recifais rasos e iluminados.",
        "status_conservacao": "Nao avaliado",
        "foto_url": "/media/especies/Condylactis_gigantea.jpg",
        "credito_imagem": "Acervo local do projeto",
        "fonte_imagem_url": "/media/especies/Condylactis_gigantea.jpg",
        "fonte_url": ""
      },
      {
        "id": 6,
        "nome_comum": "Budiao-azul",
        "nome_cientifico": "Sparisoma axillare",
        "tipo": "PEIXE",
        "descricao": "Peixe herbivoro importante para a dinamica do recife e controle de algas.",
        "status_conservacao": "Quase ameacado",
        "foto_url": "/media/especies/Sparisoma_axillare.jpg",
        "credito_imagem": "Acervo local do projeto",
        "fonte_imagem_url": "/media/especies/Sparisoma_axillare.jpg",
        "fonte_url": ""
      },
      {
        "id": 5,
        "nome_comum": "Cioba",
        "nome_cientifico": "Ocyurus chrysurus",
        "tipo": "PEIXE",
        "descricao": "Peixe recifal associado a fundos rochosos e coralineos do Atlantico tropical.",
        "status_conservacao": "Nao avaliado",
        "foto_url": "/media/especies/Ocyurus_chrysurus.jpeg",
        "credito_imagem": "Acervo local do projeto",
        "fonte_imagem_url": "/media/especies/Ocyurus_chrysurus.jpeg",
        "fonte_url": ""
      }
    ],
    "monitoramento_recente": {
      "data": "2026-04-10",
      "sst_atual": 28.7,
      "limite_termico": 27.0,
      "anomalia": 1.7,
      "dhw_calculado": 3.9,
      "irradiancia": 29.6,
      "turbidez": 0.28,
      "salinidade": 35.7,
      "oxigenio": 6.31,
      "nitrato": 0.51,
      "clorofila": 0.82,
      "risco_integrado": 58.0,
      "nivel_alerta": "OBSERVACAO"
    }
  }
};
