# Generated by Django 5.2.8 on 2025-11-07 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=100)),
                ('unidade', models.CharField(blank=True, max_length=20)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='aquaculture.especie')),
            ],
        ),
    ]
