# Generated by Django 5.2.8 on 2025-11-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0003_tecnicamanejo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPredicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data da medição', unique=True)),
                ('sst_atual', models.FloatField(help_text='Temperatura média da superfície (SST) do dia')),
                ('limite_termico', models.FloatField(help_text='Limite de branqueamento (Climatologia MMM)')),
                ('anomalia', models.FloatField(help_text='SST - Limite de branqueamento')),
                ('dhw_calculado', models.FloatField(help_text='Graus-Semana de Aquecimento (DHW) acumulado')),
                ('nivel_alerta', models.CharField(choices=[('SEM_RISCO', 'Sem Risco'), ('OBSERVACAO', 'Em Observação'), ('ALERTA_1', 'Alerta Nível 1'), ('ALERTA_2', 'Alerta Nível 2')], default='SEM_RISCO', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Status das Predições',
                'ordering': ['-data'],
            },
        ),
    ]
