# Generated by Django 5.1.2 on 2025-11-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0006_remove_especie_foto_url_especie_fonte_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuspredicao',
            name='irradiancia',
            field=models.FloatField(blank=True, help_text='Radiação Fotossintética (PAR)', null=True),
        ),
        migrations.AddField(
            model_name='statuspredicao',
            name='risco_integrado',
            field=models.FloatField(default=0.0, help_text='Índice de Risco Calculado (0-100)'),
        ),
        migrations.AddField(
            model_name='statuspredicao',
            name='turbidez',
            field=models.FloatField(blank=True, help_text='Turbidez/Atenuação da luz (Kd490)', null=True),
        ),
        migrations.AddField(
            model_name='statuspredicao',
            name='vento_velocidade',
            field=models.FloatField(blank=True, help_text='Velocidade do vento (m/s)', null=True),
        ),
    ]
