# Generated by Django 5.2.8 on 2025-12-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0007_statuspredicao_irradiancia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuspredicao',
            name='clorofila',
            field=models.FloatField(blank=True, help_text='Clorofila-a (mg/m³)', null=True),
        ),
        migrations.AddField(
            model_name='statuspredicao',
            name='nitrato',
            field=models.FloatField(blank=True, help_text='Nitrato (µmol/L)', null=True),
        ),
        migrations.AddField(
            model_name='statuspredicao',
            name='oxigenio',
            field=models.FloatField(blank=True, help_text='Oxigênio Dissolvido (mg/L)', null=True),
        ),
        migrations.AddField(
            model_name='statuspredicao',
            name='ph',
            field=models.FloatField(blank=True, help_text='pH da água', null=True),
        ),
        migrations.AddField(
            model_name='statuspredicao',
            name='salinidade',
            field=models.FloatField(blank=True, help_text='Salinidade (PSU)', null=True),
        ),
    ]
