# Generated by Django 5.2.8 on 2025-11-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cientifico', models.CharField(max_length=200, unique=True)),
                ('nome_comum', models.CharField(blank=True, max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('status_conservacao', models.CharField(blank=True, help_text='Ex: Vulnerável, Ameaçada, etc.', max_length=50)),
                ('foto_url', models.URLField(blank=True, max_length=500)),
            ],
        ),
    ]
