# Generated by Django 5.2.8 on 2025-11-07 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0002_parametro'),
    ]

    operations = [
        migrations.CreateModel(
            name='TecnicaManejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnicas', to='aquaculture.especie')),
            ],
        ),
    ]
