# Generated by Django 5.1.2 on 2025-11-27 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0004_statuspredicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnicamanejo',
            name='especie',
        ),
        migrations.AddField(
            model_name='especie',
            name='tipo',
            field=models.CharField(choices=[('CORAL', 'Coral'), ('PEIXE', 'Peixe'), ('INVERTEBRADO', 'Invertebrado'), ('MAMIFERO', 'Mamífero'), ('OUTRO', 'Outro')], default='CORAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='especie',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição Ecológica'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='status_conservacao',
            field=models.CharField(blank=True, help_text='Ex: Vulnerável, Ameaçada, Pouco Preocupante (IUCN)', max_length=50),
        ),
        migrations.AlterField(
            model_name='statuspredicao',
            name='anomalia',
            field=models.FloatField(help_text='SST - Limite'),
        ),
        migrations.AlterField(
            model_name='statuspredicao',
            name='dhw_calculado',
            field=models.FloatField(help_text='Graus-Semana de Aquecimento (DHW)'),
        ),
        migrations.AlterField(
            model_name='statuspredicao',
            name='limite_termico',
            field=models.FloatField(help_text='Limite de branqueamento (MMM)'),
        ),
        migrations.AlterField(
            model_name='statuspredicao',
            name='sst_atual',
            field=models.FloatField(help_text='Temperatura média da superfície (SST)'),
        ),
        migrations.DeleteModel(
            name='Parametro',
        ),
        migrations.DeleteModel(
            name='TecnicaManejo',
        ),
    ]
