# Generated by Django 5.1.2 on 2025-11-27 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0005_remove_tecnicamanejo_especie_especie_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especie',
            name='foto_url',
        ),
        migrations.AddField(
            model_name='especie',
            name='fonte_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link da Fonte/Mais informações'),
        ),
        migrations.AddField(
            model_name='especie',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='especies/'),
        ),
    ]
