# Generated by Django 5.1.2 on 2026-04-16 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0008_statuspredicao_clorofila_statuspredicao_nitrato_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalRecife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao do local')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='recifes/')),
                ('ultima_atualizacao', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Local de recife',
                'verbose_name_plural': 'Locais de recife',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='statuspredicao',
            options={'ordering': ['-data'], 'verbose_name': 'Status de predicao', 'verbose_name_plural': 'Status das Predicoes'},
        ),
        migrations.AlterField(
            model_name='especie',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descricao Ecologica'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='fonte_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Link da Fonte/Mais informacoes'),
        ),
        migrations.AlterField(
            model_name='especie',
            name='status_conservacao',
            field=models.CharField(blank=True, help_text='Ex: Vulneravel, Ameacada, Pouco Preocupante (IUCN)', max_length=50),
        ),
        migrations.AlterField(
            model_name='especie',
            name='tipo',
            field=models.CharField(choices=[('CORAL', 'Coral'), ('PEIXE', 'Peixe'), ('INVERTEBRADO', 'Invertebrado'), ('MAMIFERO', 'Mamifero'), ('OUTRO', 'Outro')], default='CORAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='statuspredicao',
            name='clorofila',
            field=models.FloatField(blank=True, help_text='Clorofila-a (mg/m3)', null=True),
        ),
        migrations.AlterField(
            model_name='statuspredicao',
            name='data',
            field=models.DateField(help_text='Data da medicao'),
        ),
        migrations.AlterField(
            model_name='statuspredicao',
            name='irradiancia',
            field=models.FloatField(blank=True, help_text='Radiacao Fotossintetica (PAR)', null=True),
        ),
        migrations.AlterField(
            model_name='statuspredicao',
            name='nitrato',
            field=models.FloatField(blank=True, help_text='Nitrato (umol/L)', null=True),
        ),
        migrations.AlterField(
            model_name='statuspredicao',
            name='nivel_alerta',
            field=models.CharField(choices=[('SEM_RISCO', 'Sem Risco'), ('OBSERVACAO', 'Em Observacao'), ('ALERTA_1', 'Alerta Nivel 1'), ('ALERTA_2', 'Alerta Nivel 2')], default='SEM_RISCO', max_length=20),
        ),
        migrations.AlterField(
            model_name='statuspredicao',
            name='oxigenio',
            field=models.FloatField(blank=True, help_text='Oxigenio Dissolvido (mg/L)', null=True),
        ),
        migrations.AlterField(
            model_name='statuspredicao',
            name='ph',
            field=models.FloatField(blank=True, help_text='pH da agua', null=True),
        ),
        migrations.AlterField(
            model_name='statuspredicao',
            name='risco_integrado',
            field=models.FloatField(default=0.0, help_text='Indice de Risco Calculado (0-100)'),
        ),
        migrations.AlterField(
            model_name='statuspredicao',
            name='sst_atual',
            field=models.FloatField(help_text='Temperatura media da superficie (SST)'),
        ),
        migrations.AlterField(
            model_name='statuspredicao',
            name='turbidez',
            field=models.FloatField(blank=True, help_text='Turbidez/Atenuacao da luz (Kd490)', null=True),
        ),
        migrations.AddField(
            model_name='especie',
            name='locais',
            field=models.ManyToManyField(blank=True, related_name='especies', to='aquaculture.localrecife'),
        ),
        migrations.AddField(
            model_name='statuspredicao',
            name='local_recife',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoramentos', to='aquaculture.localrecife'),
        ),
        migrations.AddConstraint(
            model_name='statuspredicao',
            constraint=models.UniqueConstraint(fields=('local_recife', 'data'), name='aquaculture_unique_statuspredicao_local_data'),
        ),
    ]
