# Generated by Django 5.2.8 on 2026-07-25 02:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0012_especie_credito_imagem_especie_fonte_imagem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='localrecife',
            name='area_km2',
            field=models.FloatField(blank=True, help_text='Area aproximada da zona recifal em km2', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='localrecife',
            name='fonte_coordenadas',
            field=models.CharField(blank=True, help_text='De onde vieram as coordenadas (rastreabilidade). Ex: ICMBio, Allen Coral Atlas', max_length=300),
        ),
        migrations.AddField(
            model_name='localrecife',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Graus decimais, negativo no hemisferio sul. Ex: -17.972', null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AddField(
            model_name='localrecife',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Graus decimais, negativo a oeste de Greenwich. Ex: -38.688', null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AddField(
            model_name='localrecife',
            name='profundidade_media_m',
            field=models.FloatField(blank=True, help_text='Profundidade media do recife em metros', null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddConstraint(
            model_name='localrecife',
            constraint=models.CheckConstraint(condition=models.Q(('latitude__isnull', True), models.Q(('latitude__gte', -90.0), ('latitude__lte', 90.0)), _connector='OR'), name='aquaculture_localrecife_latitude_valida'),
        ),
        migrations.AddConstraint(
            model_name='localrecife',
            constraint=models.CheckConstraint(condition=models.Q(('longitude__isnull', True), models.Q(('longitude__gte', -180.0), ('longitude__lte', 180.0)), _connector='OR'), name='aquaculture_localrecife_longitude_valida'),
        ),
    ]
