# Generated by Django 5.1.2 on 2026-05-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0012_especie_credito_imagem_especie_fonte_imagem_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetCatalogo',
            fields=[
                ('id', models.SlugField(max_length=160, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('resumo', models.TextField(blank=True, verbose_name='Resumo do dataset')),
                ('fonte', models.CharField(max_length=120)),
                ('tipo_dado', models.CharField(max_length=120)),
                ('localizacao', models.CharField(blank=True, max_length=200)),
                ('local_slug', models.SlugField(blank=True, max_length=120)),
                ('estado', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('formato', models.CharField(blank=True, max_length=50)),
                ('recorte_temporal', models.CharField(choices=[('intervalo', 'Intervalo'), ('publicacao', 'Publicacao')], default='intervalo', max_length=20)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('data_publicacao', models.DateField(blank=True, null=True)),
                ('periodo_rotulo', models.CharField(blank=True, max_length=80)),
                ('tamanho_mb', models.FloatField(blank=True, null=True)),
                ('url_download', models.CharField(blank=True, max_length=500)),
                ('ordem_exibicao', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dataset do catalogo',
                'verbose_name_plural': 'Datasets do catalogo',
                'ordering': ['ordem_exibicao', 'titulo'],
            },
        ),
    ]
