# Generated by Django 5.1.2 on 2026-05-07 23:14

from datetime import date

from django.db import migrations


DATASETS_INICIAIS = [
    {
        'id': 'copernicus_sst_abrolhos_2026_03',
        'titulo': 'Temperatura da superficie do mar - Abrolhos',
        'tipo_dado': 'Climatico',
        'recorte_temporal': 'intervalo',
        'data_inicio': date(2026, 3, 1),
        'data_fim': date(2026, 3, 31),
        'data_publicacao': None,
        'periodo_rotulo': 'Mar/2026',
        'estado': 'Bahia',
        'cidade': 'Caravelas',
        'localizacao': 'Parque Nacional Marinho de Abrolhos',
        'local_slug': 'abrolhos-ba',
        'fonte': 'Copernicus',
        'tamanho_mb': 1843.2,
        'formato': 'CSV',
        'resumo': 'Serie mensal de temperatura da superficie do mar usada para acompanhamento termico do recife.',
        'url_download': '/dados/sst.csv',
        'ordem_exibicao': 1,
        'ativo': True,
    },
    {
        'id': 'noaa_dhw_abrolhos_2026_03',
        'titulo': 'Degree Heating Week - Banco dos Abrolhos',
        'tipo_dado': 'Oceanografico',
        'recorte_temporal': 'intervalo',
        'data_inicio': date(2026, 3, 1),
        'data_fim': date(2026, 3, 31),
        'data_publicacao': None,
        'periodo_rotulo': 'Mar/2026',
        'estado': 'Bahia',
        'cidade': 'Caravelas',
        'localizacao': 'Parque Nacional Marinho de Abrolhos',
        'local_slug': 'abrolhos-ba',
        'fonte': 'NOAA',
        'tamanho_mb': 420.0,
        'formato': 'NetCDF',
        'resumo': 'Camada mensal de aquecimento acumulado para monitoramento de estresse termico.',
        'url_download': '/dados/dhw.csv',
        'ordem_exibicao': 2,
        'ativo': True,
    },
    {
        'id': 'inventario_biodiversidade_abrolhos_2026_q1',
        'titulo': 'Inventario de biodiversidade recifal - Abrolhos',
        'tipo_dado': 'Biodiversidade',
        'recorte_temporal': 'publicacao',
        'data_inicio': None,
        'data_fim': None,
        'data_publicacao': date(2026, 4, 6),
        'periodo_rotulo': 'Abr/2026',
        'estado': 'Bahia',
        'cidade': 'Caravelas',
        'localizacao': 'Parque Nacional Marinho de Abrolhos',
        'local_slug': 'abrolhos-ba',
        'fonte': 'Projeto Coral Brasil',
        'tamanho_mb': 48.0,
        'formato': 'JSON',
        'resumo': 'Levantamento consolidado de especies associadas ao recife e suas ocorrencias.',
        'url_download': '/dados/biodiversidade-abrolhos.json',
        'ordem_exibicao': 3,
        'ativo': True,
    },
    {
        'id': 'microbioma_picaozinho_2026_03',
        'titulo': 'Microbioma de agua recifal - Picaozinho',
        'tipo_dado': 'Microbioma',
        'recorte_temporal': 'intervalo',
        'data_inicio': date(2026, 3, 10),
        'data_fim': date(2026, 3, 24),
        'data_publicacao': None,
        'periodo_rotulo': 'Mar/2026',
        'estado': 'Paraiba',
        'cidade': 'Joao Pessoa',
        'localizacao': 'Recife de Picaozinho',
        'local_slug': 'picaozinho-pb',
        'fonte': 'NCBI',
        'tamanho_mb': 3174.4,
        'formato': 'FASTQ',
        'resumo': 'Sequenciamento metagenomico para avaliacao microbiana do ambiente recifal.',
        'url_download': '',
        'ordem_exibicao': 4,
        'ativo': True,
    },
    {
        'id': 'genetico_abrolhos_2026_q1',
        'titulo': 'Banco genetico de corais brasileiros - Abrolhos',
        'tipo_dado': 'Genetico',
        'recorte_temporal': 'publicacao',
        'data_inicio': None,
        'data_fim': None,
        'data_publicacao': date(2026, 4, 5),
        'periodo_rotulo': 'Abr/2026',
        'estado': 'Bahia',
        'cidade': 'Caravelas',
        'localizacao': 'Parque Nacional Marinho de Abrolhos',
        'local_slug': 'abrolhos-ba',
        'fonte': 'NCBI',
        'tamanho_mb': 95.0,
        'formato': 'FASTA',
        'resumo': 'Compilado genetico com sequencias de referencia para especies coralineas.',
        'url_download': '',
        'ordem_exibicao': 5,
        'ativo': True,
    },
    {
        'id': 'imagem_porto_2026_04',
        'titulo': 'Mosaico fotografico subaquatico - Porto de Galinhas',
        'tipo_dado': 'Imagem',
        'recorte_temporal': 'intervalo',
        'data_inicio': date(2026, 4, 1),
        'data_fim': date(2026, 4, 12),
        'data_publicacao': None,
        'periodo_rotulo': 'Abr/2026',
        'estado': 'Pernambuco',
        'cidade': 'Ipojuca',
        'localizacao': 'Piscinas Naturais de Porto de Galinhas',
        'local_slug': 'porto-de-galinhas-pe',
        'fonte': 'Projeto Coral Brasil',
        'tamanho_mb': 2457.6,
        'formato': 'GeoTIFF',
        'resumo': 'Colecao de imagens georreferenciadas para inspecao visual do recife.',
        'url_download': '/dados/mosaico-porto.tif',
        'ordem_exibicao': 6,
        'ativo': True,
    },
    {
        'id': 'relatorio_picaozinho_2026_04',
        'titulo': 'Relatorio tecnico de campo - Picaozinho',
        'tipo_dado': 'Relatorio',
        'recorte_temporal': 'publicacao',
        'data_inicio': None,
        'data_fim': None,
        'data_publicacao': date(2026, 4, 18),
        'periodo_rotulo': 'Abr/2026',
        'estado': 'Paraiba',
        'cidade': 'Joao Pessoa',
        'localizacao': 'Recife de Picaozinho',
        'local_slug': 'picaozinho-pb',
        'fonte': 'Projeto Coral Brasil',
        'tamanho_mb': 12.0,
        'formato': 'PDF',
        'resumo': 'Relatorio com observacoes de campo, fotografias e anotacoes de amostragem.',
        'url_download': '/dados/relatorio-picaozinho.pdf',
        'ordem_exibicao': 7,
        'ativo': True,
    },
    {
        'id': 'modelo_branqueamento_nordeste_2026_q2',
        'titulo': 'Modelo preditivo de branqueamento - Costa Nordeste',
        'tipo_dado': 'Modelo preditivo',
        'recorte_temporal': 'publicacao',
        'data_inicio': None,
        'data_fim': None,
        'data_publicacao': date(2026, 4, 22),
        'periodo_rotulo': 'Abr/2026',
        'estado': 'Regional',
        'cidade': 'Costa Nordeste',
        'localizacao': 'Costa Nordeste',
        'local_slug': '',
        'fonte': 'Projeto Coral Brasil',
        'tamanho_mb': 680.0,
        'formato': 'Parquet',
        'resumo': 'Saida consolidada de um modelo regional para risco de branqueamento coralino.',
        'url_download': '/dados/modelo-branqueamento.parquet',
        'ordem_exibicao': 8,
        'ativo': True,
    },
]


def seed_datasetcatalogo(apps, schema_editor):
    DatasetCatalogo = apps.get_model('aquaculture', 'DatasetCatalogo')

    for dataset in DATASETS_INICIAIS:
        dataset_id = dataset['id']
        defaults = {key: value for key, value in dataset.items() if key != 'id'}
        DatasetCatalogo.objects.update_or_create(id=dataset_id, defaults=defaults)


def unseed_datasetcatalogo(apps, schema_editor):
    DatasetCatalogo = apps.get_model('aquaculture', 'DatasetCatalogo')
    dataset_ids = [dataset['id'] for dataset in DATASETS_INICIAIS]
    DatasetCatalogo.objects.filter(id__in=dataset_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0013_datasetcatalogo'),
    ]

    operations = [
        migrations.RunPython(seed_datasetcatalogo, unseed_datasetcatalogo),
    ]
