# Generated by Django 5.2.8 on 2026-07-25 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0014_seed_coordenadas_locais'),
        ('aquaculture', '0014_seed_datasetcatalogo'),
    ]

    operations = [
    ]
