# Generated by Django 5.2.8 on 2026-07-25 03:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0016_remove_seed_ficticio_datasetcatalogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoIngestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(max_length=60)),
                ('inicio_periodo', models.DateField(blank=True, null=True)),
                ('fim_periodo', models.DateField(blank=True, null=True)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('parcial', 'Parcial'), ('falha', 'Falha')], max_length=10)),
                ('registros_gravados', models.PositiveIntegerField(default=0)),
                ('registros_rejeitados', models.PositiveIntegerField(default=0)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('local_recife', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='execucoes_ingestao', to='aquaculture.localrecife')),
            ],
            options={
                'verbose_name': 'Execucao de ingestao',
                'verbose_name_plural': 'Execucoes de ingestao',
                'ordering': ['-iniciado_em'],
                'indexes': [models.Index(fields=['fonte', '-iniciado_em'], name='aquaculture_fonte_339cc7_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicaoAmbiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Data da medicao (UTC)')),
                ('variavel', models.CharField(choices=[('sst', 'Temperatura da superficie do mar (°C)'), ('dhw', 'Degree Heating Week (°C·semana)'), ('baa', 'Bleaching Alert Area (0-5)'), ('hotspot', 'Coral Bleaching HotSpot (°C)'), ('sst_anomalia', 'Anomalia de SST (°C)'), ('salinidade', 'Salinidade (PSU)'), ('oxigenio', 'Oxigenio dissolvido (mmol/m³)'), ('kd490', 'Atenuacao da luz (m⁻¹)'), ('clorofila', 'Clorofila-a (mg/m³)'), ('par', 'Radiacao fotossinteticamente ativa (µmol/m²/s)')], max_length=20)),
                ('valor', models.FloatField(blank=True, help_text='Nulo quando reprovado na validacao - jamais preencher com 0', null=True)),
                ('unidade', models.CharField(max_length=40)),
                ('fonte', models.CharField(help_text='Slug do conector. Ex: noaa_crw', max_length=60)),
                ('dataset_id', models.CharField(blank=True, max_length=160)),
                ('quality_flag', models.CharField(choices=[('ok', 'Aprovada'), ('degradado', 'Aprovada com ressalva'), ('invalido', 'Reprovada na validacao fisica')], default='ok', max_length=12)),
                ('observacao', models.TextField(blank=True, help_text='Motivo do flag quando nao for "ok"')),
                ('data_coleta', models.DateTimeField(auto_now=True)),
                ('local_recife', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='aquaculture.localrecife')),
            ],
            options={
                'verbose_name': 'Medicao ambiental',
                'verbose_name_plural': 'Medicoes ambientais',
                'ordering': ['-data', 'variavel'],
                'indexes': [models.Index(fields=['local_recife', 'data'], name='aquaculture_local_r_ad77b0_idx'), models.Index(fields=['variavel', 'data'], name='aquaculture_variave_b4854a_idx')],
                'constraints': [models.UniqueConstraint(fields=('local_recife', 'data', 'variavel', 'fonte'), name='aquaculture_unique_medicao_local_data_variavel_fonte')],
            },
        ),
    ]
