# Generated by Django 5.2.8 on 2026-07-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0017_execucaoingestao_medicaoambiental'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaoambiental',
            name='variavel',
            field=models.CharField(choices=[('sst', 'Temperatura da superficie do mar (°C)'), ('dhw', 'Degree Heating Week (°C·semana)'), ('baa', 'Bleaching Alert Area (0-5)'), ('baa_area_alerta', 'Fracao da area em Alerta Nivel 1+ (0-1)'), ('hotspot', 'Coral Bleaching HotSpot (°C)'), ('sst_anomalia', 'Anomalia de SST (°C)'), ('salinidade', 'Salinidade (PSU)'), ('oxigenio', 'Oxigenio dissolvido (mmol/m³)'), ('kd490', 'Atenuacao da luz (m⁻¹)'), ('clorofila', 'Clorofila-a (mg/m³)'), ('par', 'Radiacao fotossinteticamente ativa (µmol/m²/s)')], max_length=20),
        ),
    ]
