# Generated by Django 5.2.8 on 2026-07-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0018_alter_medicaoambiental_variavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetcatalogo',
            name='fonte_medicao',
            field=models.CharField(blank=True, help_text='Valor de MedicaoAmbiental.fonte que este dataset alimenta (ex.: noaa_crw, copernicus). Vazio = referencia externa, nao espelhada no banco.', max_length=60),
        ),
        migrations.AddField(
            model_name='datasetcatalogo',
            name='variaveis_medicao',
            field=models.CharField(blank=True, help_text='Variaveis canonicas separadas por virgula (ex.: "sst,dhw"). Vazio com fonte preenchida = todas as variaveis daquela fonte.', max_length=300),
        ),
    ]
