# Generated by Django 5.2.8 on 2026-08-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0026_corrigir_proveniencia_fotos_especies'),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaoingestao',
            name='correlacao',
            field=models.CharField(blank=True, help_text='Identificador do fluxo no arquivo de log. Procure por ele em backend/logs/coral.jsonl para ver o rastro completo.', max_length=32, verbose_name='Correlacao no log'),
        ),
        migrations.AddIndex(
            model_name='execucaoingestao',
            index=models.Index(fields=['correlacao'], name='aquaculture_correla_45c49e_idx'),
        ),
    ]
