# Generated by Django 5.2.8 on 2026-08-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0027_correlacao_na_execucao_ingestao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarefa', models.CharField(max_length=80)),
                ('unidade', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('concluido', 'Concluido'), ('falhou', 'Falhou'), ('em_andamento', 'Em andamento (ou interrompido)')], default='em_andamento', max_length=12)),
                ('tentativas', models.PositiveIntegerField(default=0)),
                ('evidencia', models.JSONField(blank=True, default=dict)),
                ('erro', models.TextField(blank=True)),
                ('correlacao', models.CharField(blank=True, max_length=32)),
                ('iniciado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('concluido_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Checkpoint',
                'verbose_name_plural': 'Checkpoints',
                'ordering': ['tarefa', 'unidade'],
                'indexes': [models.Index(fields=['tarefa', 'status'], name='aquaculture_tarefa_fd6e85_idx')],
                'constraints': [models.UniqueConstraint(fields=('tarefa', 'unidade'), name='checkpoint_unico_por_unidade')],
            },
        ),
    ]
