# Generated by Django 5.2.8 on 2026-08-12 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquaculture', '0028_checkpoints_de_retomada'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetcatalogo',
            name='download_exige_conta',
            field=models.BooleanField(default=False, help_text='Marque quando url_download apontar para um endpoint deste projeto que exige conta aprovada. Falso para link do provedor externo.', verbose_name='Download exige conta aprovada'),
        ),
    ]
